### ISSUE TITLE
File permissions on Export/Import lost

### ISSUE THREAD

**Issue by tandersoft** [RedhawkSDR/eclipse-gov.redhawk.ide#7]
If I create an archive by export from several projects, RedHawk creates a zip file.  If I move that file to another machine with RedHawk installed and import the archive, I get all my projects, but all the file permissions are lost, so the executable files (eg, build.sh, cpp/build.sh, cpp/configure and any component executable all have the execution bit off, so I have to manually go into the directory to set the bit on on those files in order to use the component or re-build it.  It looks like the preserve permissions option is not being used in the creation of the archive zip.

**Comment by drwille** [comment]
The export function in the REDHAWK IDE is inherited from Eclipse. Eclipse produces a platform-agnostic zip (or tar), therefore Unix permissions are not preserved, nor are symbolic links (the files are copied). Because Redhawk component, device and service projects require both of these aspects, I would recommend that you not use the Eclipse export function for those project types.

**Comment by tandersoft** [comment]
And use what instead?  How should one move a project to a different machine?

**Comment by ryanbauman** [comment]
Instead of using Eclipse's export function, we recommend using tar via the command line or a VCS like git to transfer source between hosts.
